services:
  backend:
    build: ./
    container_name: app-backend
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
  frontend:
    build: ./client
    container_name: app-frontend
    ports:
      - "5173:80"
